# Generated by Django 4.2.10 on 2024-03-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="vehicle_color",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="vehicle_make",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="vehicle_model",
            field=models.CharField(default="", max_length=64),
        ),
    ]
